"""Add classificacao to demands

Revision ID: 178381d96034
Revises: d8d98430ec43
Create Date: 2025-12-02 20:51:06.300258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178381d96034'
down_revision = 'd8d98430ec43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classificacao', sa.Enum('H', 'A', 'T', 'M', name='classificacao_enum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demands', schema=None) as batch_op:
        batch_op.drop_column('classificacao')

    # ### end Alembic commands ###
