"""Add approver names to config

Revision ID: 357786087db2
Revises: 178381d96034
Create Date: 2025-12-02 21:03:07.675060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357786087db2'
down_revision = '178381d96034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_aprovador_1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nome_aprovador_2', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_column('nome_aprovador_2')
        batch_op.drop_column('nome_aprovador_1')

    # ### end Alembic commands ###
