"""Initial migration with HMC

Revision ID: 5a1c96fbc325
Revises: 
Create Date: 2025-12-03 13:46:03.870088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a1c96fbc325'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_aprovador_1', sa.String(length=120), nullable=True),
    sa.Column('email_aprovador_2', sa.String(length=120), nullable=True),
    sa.Column('nome_aprovador_1', sa.String(length=100), nullable=True),
    sa.Column('nome_aprovador_2', sa.String(length=100), nullable=True),
    sa.Column('email_executor_default', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hmc', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('VISUALIZADOR', 'EMITENTE', 'APROVADOR_1', 'APROVADOR_2', 'EXECUTOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('hmc')
    )
    op.create_table('bug_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='bugstatus'), nullable=False),
    sa.Column('developer_response', sa.Text(), nullable=True),
    sa.Column('response_at', sa.DateTime(), nullable=True),
    sa.Column('responder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['responder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('problema', sa.Text(), nullable=False),
    sa.Column('processo', sa.String(length=100), nullable=False),
    sa.Column('equipamento', sa.String(length=100), nullable=False),
    sa.Column('gut', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE_APROVACAO_1', 'REJEITADO_APROVACAO_1', 'PENDENTE_APROVACAO_2', 'REJEITADO_APROVACAO_2', 'AGUARDANDO_EXECUCAO', 'EXECUTANDO', 'CONCLUIDO', name='demandstatus'), nullable=False),
    sa.Column('classificacao', sa.Enum('H', 'A', 'T', 'M', name='classificacao_enum'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demand_id', sa.Integer(), nullable=False),
    sa.Column('aprovador_id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('APROVADO', 'REJEITADO', name='approvalstatus'), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aprovador_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demand_id', sa.Integer(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=False),
    sa.Column('descricao_atividade', sa.Text(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('foto_final', sa.String(length=255), nullable=True),
    sa.Column('pm04_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], ),
    sa.ForeignKeyConstraint(['executor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demand_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demand_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE_APROVACAO_1', 'REJEITADO_APROVACAO_1', 'PENDENTE_APROVACAO_2', 'REJEITADO_APROVACAO_2', 'AGUARDANDO_EXECUCAO', 'EXECUTANDO', 'CONCLUIDO', name='demandstatus'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_history')
    op.drop_table('photos')
    op.drop_table('executions')
    op.drop_table('approvals')
    op.drop_table('system_updates')
    op.drop_table('demands')
    op.drop_table('bug_reports')
    op.drop_table('users')
    op.drop_table('app_config')
    # ### end Alembic commands ###
